title: 'Nelson Silva'
description: 'My career as a Frontend Developer (Profile, Resume, Portfolio and Blog)'
keywords: 'technology, computing, programming, frontend, developer, code, nelsonsilvadev, nelsonsilva, nelson silva'
url: 'https://nelsonsilvadev.com'

development: false

organization:
  name: 'Caffeine Algorithm'
  email: 'contacto@caffeinealgorithm.com'
  youtube_id: 'UCdt_qK8rmpxrq942ZFIqxvQ'
  youtube_name: 'CaffeineAlgorithm'
  linkedin: 'caffeinealgorithm'
  instagram: 'caffeinealgorithm'
  twitch: 'caffeinealgorithm'
  github: 'caffeinealgorithm'
  website: 'https://caffeinealgorithm.com/'

author:
  name: 'Nelson Silva'
  username: 'nelsonsilvadev'
  date_of_birth: 'July 5, 1995'
  phone_number: '+351913416022'
  location: 'Porto, Portugal'
  email: 'contact@nelsonsilvadev.com'
  bio: 'A human. Being. Coffee lover.'
  linkedin: 'nelsonsilvadev'
  github: 'nelsonsilvadev'
  instagram: 'nelsonsilvadev'
  website: 'https://nelsonsilvadev.com/'

google:
  tag_manager: 'GTM-K6M9N4W'
  analytics: 'UA-76965623-2'
  verify: 'ajVPbFZ5Vbuj0FC0vgFM27c4n0WhIuqqUVTlaJuaKVk'
  ad_client: 'ca-pub-9627952229249296'

google_site_verification: 'ajVPbFZ5Vbuj0FC0vgFM27c4n0WhIuqqUVTlaJuaKVk'

social:
  name: 'Nelson Silva'
  links:
    - 'https://github.com/nelsonsilvadev'
    - 'https://www.linkedin.com/in/nelsonsilvadev'
    - 'https://www.instagram.com/nelsonsilvadev'
    - 'https://www.youtube.com/c/CaffeineAlgorithm'

locale: 'en_US'

seo_paginator_message: 'Page %<current>s of %<total>s | '

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

destination: _site
paginate: 6
paginate_path: /blog/page/:num/
permalink: /blog/:year:month:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins: ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-seo-tag']
exclude: ['README.md']
